### PR TITLE
perf: improve mongo query performance

### PR DESCRIPTION
**Pull request by vladimirmutafov**
Fixes: https://github.com/javers/javers/issues/1039

### CODE REVIEW

**Comment by vladimirmutafov** [comment]
@bartoszwalacik If this approach is ok, should I also add an index for `globalId.ownerId.cdoId`?

**Comment by bartoszwalacik** [comment]
I will add the index

**Comment by bartoszwalacik** [comment]
merged from here https://github.com/javers/javers/pull/1368, thanks @vladimirmutafov

**Comment by vladimirmutafov** [comment]
@bartoszwalacik thanks a lot!

**Pull request closed without merging**
