### PR TITLE
Use Repository instead of CrudRepository

### PR DESCRIPTION
**Pull request by sebastian-sch**
In our case CrudRepository isn't not working because we directly extend the Repository. 

I think it is in general a good idea, to make it as flexible as possible.

[Review on Reviewable](https://reviewable.io/reviews/javers/javers/145)

### CODE REVIEW

**Comment by bartoszwalacik** [comment]
but save() and delete() methods are defined in CrudRepository, Repository is only a marker interface

so is this pointcut typesafe?

```
@After("execution(public * save(..)) && this(org.springframework.data.repository.Repository)")
```

**Comment by bartoszwalacik** [comment]
if you do not extend CrudRepository, how you define your save() and delete() methods?

**Comment by bartoszwalacik** [comment]
@sebastian-sch are you there? :)

**Comment by sebastian-sch** [comment]
Sorry for the delay, I was quite busy. The reason why I use the Repository instead of CrudRepository is, that I don't allow delete. I created my own CrudRepository with the same save() but without delete, for this the logic from JaversAuditableRepositoryAspect isn't working. 

Another option instead of changing    
```
@After("execution(public * save(..)) && this(org.springframework.data.repository.Repository)")
```
would be, to make JaversAuditableRepositoryAspect extendable  
to overwrite 
```
   @After("execution(public * delete(..)) && this(org.springframework.data.repository.Repository)")
    public void onDeleteExecuted(JoinPoint pjp)  {
        onVersionEvent(pjp, deleteHandler);
    }
```
or
```
    @After("execution(public * save(..)) && this(org.springframework.data.repository.Repository)")
    public void onSaveExecuted(JoinPoint pjp) {
        onVersionEvent(pjp, saveHandler);
    }
```

**Comment by pawelszymczyk** [comment]
Hi Sebastian

Firstly thansk for a response, now your case is very clear. Aspectj does not allowed to extend concrete aspects, JaversAuditableRepositoryAspect is concrete so there is no possibility to change advices. Proper solution is to separate logic and advices, logic should be moved to abstract aspect, and advices should stay at contrete class as a default implementation, then you can extend abstract aspect and provide your own advices. Do you want to provide this solution in another pull request?

**Comment by bartoszwalacik** [comment]
closing due to lack of activity

**Pull request closed without merging**
