### PR TITLE
Avoid nested DiffIgnored ValueObject being compare

### PR DESCRIPTION
**Pull request by hank-cp**
Set gsonBuilder exclusionStrategies to avoid nested ValueObject circular reference.

### CODE REVIEW

**Comment by bartoszwalacik** [comment]
why this strategy? javers doesn't serialize user's domain objets

**Comment by hank-cp** [comment]
Sorry, I didn't explain this issue clear enough. The problem is not about comparison, but about committing against MongoRepository. I add a few test case, hope that would explain the problem.

**Comment by bartoszwalacik** [comment]
so, it's more gson problem than javers issue

**Comment by bartoszwalacik** [comment]
you have a wrong mapping for CrossReferenceObjectA.
Obviously, this is a complext object so you should map it as ValueObject (not Value)
It's enough to remove @Value ann, see
https://github.com/javers/javers/commit/7ee9f6de22263f41be17a11a136e718ecd442415

**Comment by hank-cp** [comment]
@bartoszwalacik Actually I do need to mark CrossReferenceObjectA/B as `@Value`, three reasons in my thought:
1. In my case, CrossReferenceObjectA/B are very general, fundamental class, most of other business class will refer them, and they change quite a lot and often.
2. These objects basically have a little bit complex, cross reference relation graph, according to my observation, committing them as `@ValueObject`, the javers repository size will be glowing very fast, a little bit out of control.
3. I have to implement CustomPropertyComparator for these classes so it could compare by my custom algorithm rather than Javers general comparison algorithm. I think this will required `@Value` or `JaversBuilder.javers().registerValue()` (correct my if I am wrong).

**Comment by bartoszwalacik** [comment]
Ok, makes sense, if @Value fits better to your model then you should be able to choose it. Give me a while and I will merge

**Comment by bartoszwalacik** [comment]
released in 2.5.0

**Pull request merged**
