### PR TITLE
Make HEAD collection name configurable

### PR DESCRIPTION
**Pull request by egasimov**
PR intended to resolve [issue-1254](https://github.com/javers/javers/issues/1254)

### CODE REVIEW

**Review by jrasuljafarov — APPROVED** [review]

**Review by mmushfiq — APPROVED** [review]

**Comment by egasimov** [comment]
Hi @bartoszwalacik, 

Have u got any chance to review PR, please?

**Comment by egasimov** [comment]
Great, looking forward to the release tomorrow! Thank you for considering my contribution.

**Comment by egasimov** [comment]
Hi @bartoszwalacik , Could you please assist to release the versions: [javers-6.9.0](https://github.com/javers/javers/releases/tag/javers-6.9.0) , [javers-6.9.1](https://github.com/javers/javers/releases/tag/javers-6.9.1) on [mvn repository](https://mvnrepository.com/artifact/org.javers) ?

FYI:
I observed that the build pipeline for 6.9.0 failed.([here](https://app.travis-ci.com/github/javers/javers/builds/260139028)) due to socket timeout exception, probably it might be cause why not released to mvn repository

**Comment by bartoszwalacik** [comment]
@egasimov right, I tried to release it manually via https://oss.sonatype.org/ GUI, but without success, unfortunately our CI pipeline on Travis is blocked due to issue on the Travis side, see https://app.travis-ci.com/github/javers/javers/builds . I work with Travis support to solve that issue. If it is unblocked I will retry. Please be patient

**Comment by bartoszwalacik** [comment]
ok, artifacts should be in the Central in a few hours

**Comment by egasimov** [comment]
@bartoszwalacik Thanks, I've just checked version: 6.9.1 and it is ok.

But as note, 6.9.0 couldn't be found in central just fyi

**Comment by bartoszwalacik** [comment]
@egasimov yes, 6.9.0 will be skipped, still don't see 6.9.1 in the Central

**Comment by egasimov** [comment]
@bartoszwalacik Got it. 
[From here](https://repo1.maven.org/maven2/org/javers/javers-core/6.9.1/) I can see

**Comment by bartoszwalacik** [comment]
ok, for the official release, I need to wait until it will be searchable in the Central https://search.maven.org/artifact/org.javers/javers-spring-mongo

**Comment by bartoszwalacik** [comment]
released in 6.9.1

**Pull request closed without merging**
