### PR TITLE
Allow to change Column Names for SQL

### PR DESCRIPTION
**Pull request by gustavodsf**
In a project of [CESAR](https://www.cesar.org.br/) the client has a specific rule of the database creation, so we needed to customizes the names of the entire database, so we needed to add this type of configuration to javers. So your have to add the configuration below on your application.properties

```
javers.sqlGlobalIdTableName=my_global_id
javers.sqlCommitTableName=my_commit
javers.sqlSnapshotTableName=my_snapshot
javers.sqlCommitPropertyTableName=my_commit_property
```
```
javers.sqlGlobalIdPKColunmName= global_pk
javers.sqlGlobalIdLocalIdColumnName= global_id_local
javers.sqlGlobalIdFragmentColumnName= global_fragment
javers.sqlGlobalIdTypeNameColumnName= global_type_name
javers.sqlGlobalIdOwnerIDFKColumnName= global_id_owner_fk
javers.sqlCommitPKColumnName= commit_pk
javers.sqlCommitAuthorColumnName= commit_author
javers.sqlCommitCommitDateColumnName= commit_date
javers.sqlCommitCommitDateInstantColumnName= commit_instant
javers.sqlCommitCommitIdColumName= commit_commit_id
javers.sqlCommitPropertyCommitFKColumnName= commit_property_id
javers.sqlCommitPropertyNameColumnName= commit_property_name
javers.sqlCommitPropertyValueColumnName= commit_property_value
javers.sqlSnapshotPKColumnName= snapshot_pk
javers.sqlSnapshotCommitFKColumnName= snapshot_commit_fk
javers.sqlSnapshotGlobalIdFKColumnName= snapshot_global_fk
javers.sqlSnapshotTypeColumnName= snapshot_type
javers.sqlSnapshotVersionColumnName= snapshot_version
javers.sqlSnapshotStateColumnName= snapshot_state
javers.sqlSnapshotChangedColumnName= snapshot_changed
javers.sqlSnapshotManagedTypeColumnName= snapshot_managed_type
```

### CODE REVIEW

**Comment by bartoszwalacik** [comment]
Please remove all you local files generated by eclipse and the build is failing

**Comment by gustavodsf** [comment]
> Please remove all you local files generated by eclipse, and the build is failing

Sorry, I will remove this generated files, but you have some adivice about the error on travis, because i did ran the test on localy and i received success, the error on travis is: Caused by: org.postgresql.util.PSQLException: ERROR: relation "jv_commit_property" already exists, do you have some clue ?

**Comment by bartoszwalacik** [comment]
your local files are still there ...

**Comment by bartoszwalacik** [comment]
It's really easy to check, Files Changed Tab - 56 files ...

**Comment by gustavodsf** [comment]
Sorry! I didn't saw that had eclipse file inside the directory, but i don't  know why it is breaking travis, because when i run ./gradlew test, it return build success, so i have to run another command to run this tests ?

**Comment by bartoszwalacik** [comment]
you can run all tests for all databases locally if you have docker,

run all tests in this package 
javers-persistence-sql : org.javers.repository.sql.integration.docker

**Comment by bartoszwalacik** [comment]
@gustavodsf could you please create a clean PR from your final work? try to squash your commits and remove all of your local files, they are back again as far as I see

**Pull request closed without merging**
