### PR TITLE
Shallow multi edge

### PR DESCRIPTION
**Pull request by FmeuMan**
Should do the work for #528.
Dont know if is it worth it to handle collections with both entities and shallow entities. This doesn't work for now.

### CODE REVIEW

**Comment by bartoszwalacik** [comment]
Hi @FmeuMan, nice PR but needs some work.
I have committed a failing test here https://github.com/javers/javers/pull/805

looks like we need to add support for class-level `@ShallowReferecne`:

The case:
```
class SnapshotEntity {
    Set<ShallowPhone> shallowPhones
}

@ShallowReference
public class ShallowPhone {
}
```

**Comment by FmeuMan** [comment]
Nice one! I'll take a look.
And thanks for the reformating :)

**Comment by FmeuMan** [comment]
Ok! Thoses additions seems a bit intrusive to me. But I don't think i can do better for now

**Comment by bartoszwalacik** [comment]
@FmeuMan I have added more test on my branch, also I did some refactoring to make this new feature more aligned with javers-core. My branch is merged and I will release it tomorrow.
So I'm closing this branch, and finally, your last commit won't be merged.

Thanks for your contribution, you have great understanding of Javers code base and tests. Your PRs are welcome.

**Pull request closed without merging**
