### PR TITLE
#398 Define schema for javers related tables 

### PR DESCRIPTION
**Pull request by ianagius**
added withSchema() to SqlRepositoryBuilder to enable users to create and use tables in a defined Schema.

As part of the change, the static table and sequence names in the FixedSchemaFactory class have been made private and access to them is made available through static getters (which check if a schema was defined).

The JaversSchemaManager has been modified to check for the javers tables if a schema has been defined.  If no schema has been defined, this resposibility to handed over to PolyJDBC.

### CODE REVIEW

**Comment by ianagius** [comment]
With regards to 1 and 2, we totally agree and will amend accordingly.

Regarding 3, we really didn't want to get involved in another project.  Having said that, we are taking a look at polyjdbc code. 

Still unsure about your suggestion to make PolyJDBC aware of the schema and not make any changes in JaVers when we consider code in JaVers like the following (found in SnapshotFilter):
```
static final String COMMIT_WITH_SNAPSHOT = 
     SNAPSHOT_TABLE_NAME 
     + " INNER JOIN " 
     + COMMIT_TABLE_NAME 
     + " ON " + COMMIT_PK 
     + " = " + SNAPSHOT_COMMIT_FK;

static final String COMMIT_WITH_SNAPSHOT_GLOBAL_ID =
     COMMIT_WITH_SNAPSHOT 
     + " INNER JOIN " + GLOBAL_ID_TABLE_NAME + " g ON g." 
     + GLOBAL_ID_PK + " = " + SNAPSHOT_GLOBAL_ID_FK 
     + " LEFT OUTER JOIN " + GLOBAL_ID_TABLE_NAME 
     + " o ON o." + GLOBAL_ID_PK + " = g." + GLOBAL_ID_OWNER_ID_FK;
```

What we can't understand is how these queries will be handled by PolyJDBC.   These queries look like they are being passed to PolyJDBC which in turn executes them immediately.  Are you suggesting that PolyJDBC rewrites these queries as they're being passed by JaVers? If this is so, then PolyJDBC needs to be aware of the tables in JaVers so this rewriting can occur.  Or are we missing something?

**Comment by bartoszwalacik** [comment]
ok, you are right, both sides (PolyJdbc and JaVers should be schema-aware) to some extent.
1. PolyJdbc's primary responsibility is schema creation (DDL's). If you pass a schema name to PolyJdbc instance, it could create all objects in this concrete schema.
2. I don't want any major changes in `JaversSchemaManager.java`, PolyJdbc should manage it
3. I'm also a committer of PolyJdbc, so I can help you to go through a Pull Request to PolyJdbc
4. You are right that JaVers can add schema prefix to table names (rewriting FROM clauses in PolyJdbc would be awkward)
5. the solution you proposed (`getGlobalIdTableName()`, etc.) can work but these methods can't be static (various JaVers instances can have various schema names).

hope we now agree on the design

**Comment by ianagius** [comment]
yes definitely. will come back to you with a new pull request

**Comment by ianagius** [comment]
created a pull request on polyjdbc side. Will create a pull request for JaVers once that is accepted.

**Comment by bartoszwalacik** [comment]
ok, seems like a good plan

**Comment by ianagius** [comment]
created an other pull request

**Comment by bartoszwalacik** [comment]
thanks, I will take a look

**Pull request closed without merging**
