### PR TITLE
Added DBRefUnproxyObjectAccessHook

### PR DESCRIPTION
**Pull request by joha78**
This extension solves problems with MongoDBs DBRef(lazy=true) annotation

### CODE REVIEW

**Comment by bartoszwalacik** [comment]
nice, but we need some test, I will write some

**Comment by joha78** [comment]
Thank you very much. I thought about doing it myself but I am not very familiar with groovy

**Comment by bartoszwalacik** [comment]
There is a problem with dependency management here. 
Adding dep to spring-data-mongo brakes JaVers, because it downgrades mong-db-driver version from 3.6 to 3.4
Look like we need to upgrade the whole javers to Spring 5 and Sprint Boot 2

**Comment by joha78** [comment]
I found another problem. If I use the new DBRefUnproxyObjectAccessHook I get some strange things in MongoDB jv_snapshots:

`
nbrDest: "EE4344D",
toPlanet: Object {
           entity: "de.spacesystems.Planet"
           cdoId: Object {
                timestamp: 1498562478
                machineIdentifier:14306734
                processIdentifier: 26005
                counter: 13820548
           },
handlerStatus: "ConfirmedByHandler"
`

Obviously something is wrong with the cdoID ?!
Any suggestions what could be wrong?

**Comment by joha78** [comment]
> There is a problem with dependency management here.
> Adding dep to spring-data-mongo brakes JaVers, because it downgrades mong-db-driver version from 3.6 to 3.4
> Look like we need to upgrade the whole javers to Spring 5 and Sprint Boot 2

I am not sure why this can be. I just reused an existing dependency in the new sub-project of javers.

**Comment by bartoszwalacik** [comment]
It looks like ObjectId, this problem is described here https://javers.org/documentation/repository-configuration/#custom-json-serialization and it's another issue to add out-of-the box support for mongo ObjectId's in JaVers. 
In this issue we are focusing on DBRefs and making JaVers work with spring-data-mongo. I'll try to upgrade JaVers to Spring 5 and Sprint Boot 2.

**Comment by bartoszwalacik** [comment]
@joha78 I have sketch of the test here https://github.com/javers/javers/pull/742/files
I can't find docs about DBRefs proxies. How does it works? How can I observe uninitialized DBRefs proxy?

**Comment by joha78** [comment]
I am not exactly sure about your question. As far as I know you can't observe uninitialized DBRefs proxy (interface LazyLoadingProxy). But if you call LazyLoadingProxy.getTarget() you get the fresh loaded Entity. Have a look at DefaultDbRefResolver to see how it works. Behind the scenes it is using a LazyLoadingInterceptor.

**Comment by bartoszwalacik** [comment]
ok will check it. I want to have a test and see how it fails without the new hook and how it passes with the hook.

**Comment by bartoszwalacik** [comment]
btw, could you please provide the second PR to javers/joha78-master branch with this test?

**Comment by joha78** [comment]
> btw, could you please provide the second PR to javers/joha78-master branch with this test?

I did, you should have a pull request.

**Comment by bartoszwalacik** [comment]
ok, I merged your second PR and made few fixes. Now I think the hook works and it's added to the starter.

see https://github.com/javers/javers/pull/742/files
is it what you need?

**Comment by bartoszwalacik** [comment]
merged from another branch, will be released as 4.0.0-RC4

**Pull request closed without merging**
