### PR TITLE
@ConditionalOnMissingBean on javers(connectionProvider) for Mongo and Sql

### PR DESCRIPTION
**Pull request by abibell**
Fix for http://stackoverflow.com/questions/39322714/javerssqlautoconfiguration-javers-not-getting-called

### CODE REVIEW

**Comment by bartoszwalacik** [comment]
@abibell I thought that this PR is about adding `@ConditionalOnMissingBean` to javers starters configuration. Then you could replace default javers bean with your javers bean with your configuration (`scanTypeName()`).
We didnt talked abould implementing `scanTypeNames()`. This is another issue - https://github.com/javers/javers/issues/263
And I think that javers should use some dedicated lib for classpath scanning.

**Comment by bartoszwalacik** [comment]
The first commit in this PR is OK, the second is not OK. I will merge if you remove the second commit. I think, the first one is enough to solve your issue

**Comment by abibell** [comment]
Oops, 2nd commit wasn't meant to come into PR. Try it now.

With regards to second issue, what would library do you have in mind to use, is it worth it? Do you see introducing the classpath scanning library can be a separate issue to getting scanTypeNames(package)?

**Comment by bartoszwalacik** [comment]
yes, there is a separate issue for that - https://github.com/javers/javers/issues/263
Some research is needed, the ann scanning lib should be small (no dependencies) and fast

**Comment by bartoszwalacik** [comment]
released in 2.2.2

**Pull request merged**
