### PR TITLE
#1257 Application-Layer Encryption of Snapshot State in SQL repository

### PR DESCRIPTION
**Pull request by c247t**
Inject symmetric String-to-String codec into SQL persistence of CdoSnapshotState

### CODE REVIEW

**Comment by bartoszwalacik** [comment]
see https://github.com/javers/javers/issues/1257

**Review by bartoszwalacik — CHANGES_REQUESTED** [review]
the change LGTM but please add a test

**Comment by bartoszwalacik** [comment]
good tests, thanks @c247t, LGTM, it will merge from this PR https://github.com/javers/javers/pull/1276

**Comment by bartoszwalacik** [comment]
merged

**Comment by bartoszwalacik** [comment]
released in 6.12

**Comment by kelunik** [comment]
@bartoszwalacik Thanks! Was just about to type that I'm looking forward to the release. 🎉

**Pull request closed without merging**
