### PR TITLE
#962 Replace references to legacy MongoClient with newer version.

### PR DESCRIPTION
**Pull request by nishkarsh**
- Replaced all the imports of `MongoClient` from `com.mongodb.MongoClient` to `com.mongodb.client.MongoClient`
- Using `MongoClients` from `com.mongodb.client` package to construct `MongoClient` which is now the recommended way.

### CODE REVIEW

**Comment by bartoszwalacik** [comment]
thanks, but looks like the build is failing, I will take a look.

**Comment by nishkarsh** [comment]
Hey @bartoszwalacik! The build was passing on local, seems like some more tests run on a different profile, I will also spend some time on it and see if I can fix it.

**Comment by bartoszwalacik** [comment]
`JaversMongoStarterIntegrationTest` fails on local for me. there are issues in Spring DI, probably as a result of changed bean's type 

```
Description:

Field mongoClient in org.javers.spring.boot.mongo.JaversMongoAutoConfiguration required a bean of type 'com.mongodb.client.MongoClient' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)
```

**Comment by nishkarsh** [comment]
Oh, this spec never executed when I ran `./gradlew build`. Running it explicitly from IntelliJ confirms that it fails. Apparently I have missed a couple of places where the legacy MongoClient is being constructed. I will soon verify and push the fixes.

**Comment by nishkarsh** [comment]
I have made all the changes. I guess the problem is with [Embedded Mongo](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo) since it still depends on the legacy Mongo. I added a `MongoClient` Bean as a test configuration since Spring, in this case, provided legacy `MongoClient`.

This, however, changes things that might require a major version bump since `MongoClientOptions` have been replaced with `MongoClientSettings` too along with the migration of legacy `MongoClient`.

Let me know if I could help in any other way! Thanks!

**Pull request merged**
